Calcul : max(score brut, score brut * (pop. Paris / pop. dép))
cedricr/100joursdezbeul pull request #112
Opened 2023-05-09 20:45 UTC by florianMo

Calcul : max(score brut, score brut * (pop. Paris / pop. dép))
Affichage d'un notice au dessus du classement, et des 2 scores dans le classement. Le score considéré pour le tri est affiché en premier.
Sur les pages départements, on affiche d'abord le brut, et ajout d'une ligne pour indiquer le score pondéré.
Constante SORT_ON pour passer d'un tri à l'autre.

https://github.com/cedricr/100joursdezbeul/issues/87

2023-05-09 20:54 UTC, florianMo commented
Pour le moment j'ai conservé les 2 types de score, et j'ai essayé de rendre ça clair à la lecture sur le site (les 2 scores sont affichés sur le classement et sur les pages département). Ca bouleverse un peu le classement donc ça peut heurter ceux qui reculent avec ce mode de calcul :). Bravo au Rhône qui passe premier !

On passe d'un mode de calcul à l'autre avec la constante `SORT_ON` (pour le leaderboard), on pourrait imaginer avoir une switch sur la page du classement pour passer de l'un à l'autre.

On pourrait aussi imaginer d'afficher le coefficient appliqué sur les page département et/ou sur le leaderboard.

Besoin d'une passe sur les textes que j'ai ajouté en mode impro :smile: 

Populations : recensement 2020 (https://fr.wikipedia.org/wiki/Liste_des_d%C3%A9partements_fran%C3%A7ais_class%C3%A9s_par_population_et_superficie#Liste_des_d%C3%A9partements)

2023-05-10 09:26 UTC, D4llo commented
Pou moi il faut un seul classement sur la page principale. J'ai une crainte de perte de lisibilité. Est-ce que comme pour le classement région, ce serait pertinent de le migrer dans une page indépendante ? On risque de sacrifier de la visibilité dans ce cas.

Une alternative serait d'ajouter un bouton pour changer d'état 

![image](https://github.com/cedricr/100joursdezbeul/assets/131776117/d149dce0-db8a-4f59-b7cd-a6a0d8770c71)

Dans un premier temps je propose de laisser le legacy en défaut et d'ajouter le pondéré activé au click

Qu'en pensez-vous ?

2023-05-10 10:03 UTC, florianMo commented
Je suis d'accord avec l'aspect lisibilité, ok aussi pour pouvoir sélectionner le mode de calcul du score. Côté UI on a 2 choix à faire : 
- score brut ou pondéré
- départements ou régions

Donc ça peut être 2 groupes de boutons radios, possiblement avec un rendu bouton actif/inactif, ou 2 switchs. Avec des radios sous forme de boutons actifs/inactifs ça pourrait donner ça :

https://github.com/cedricr/100joursdezbeul/assets/3530297/7793b315-0a37-4bd0-bc77-bafabbef95ae

2023-05-10 12:17 UTC, florianMo commented
Je vais mettre en place le switch brut/pondéré, pour département/région ça dépend de https://github.com/cedricr/100joursdezbeul/pull/79 donc je laisse de côté pour le moment. Merci pour le feedback !

Qu'est ce que vous pensez de la modif sur les pages départements (affichage du score pondéré en sous titre) ?

2023-05-10 13:22 UTC, D4llo commented
@florianMo perso je suis pour faire ça dans une autre PR/issue pour en discuter séparément.

Ce sera plus simple pour nous de nous décider et de valider les revues et les merges en conservant les PR minimalistes.

2023-05-10 13:27 UTC, florianMo commented
OK je ferais ça dans une autre PR (si on veut le faire)

2023-05-10 18:55 UTC, florianMo commented
@D4llo je viens de pousser l'ajout de la switch pour passer de score brut à score rapporté à la population. Si quelqu'un a des idées de wording c'est bienvenu, je suis pas fan de ce que j'ai mis dans les boutons (mais rien trouvé de plus simple...)

J'ai aussi viré la ligne sur les pages département qui indique le score /pop.

J'ai repris le rouge du nombre de jours restants pour le background des boutons, pareil ya ptet mieux...

https://github.com/cedricr/100joursdezbeul/assets/3530297/8e339e04-5def-4031-81d5-45050c206a19

2023-05-10 21:38 UTC, D4llo commented
Bon question pour le wording. Pourquoi pas "Score" et "Score / Habitants" ?

2023-05-11 06:14 UTC, florianMo commented
done pour le wording, et je suis passé sur le bleu du premier anneau/casserole pour le fond.

![image](https://github.com/cedricr/100joursdezbeul/assets/3530297/f0fd3c53-94d3-4aab-afa2-dac810c3fb8a)

2023-05-11 06:17 UTC, florianMo commented
et au passage ça résout #110

2023-05-12 11:59 UTC, florianMo commented
@D4llo je me rends compte que sur [le deploy-preview](https://deploy-preview-112--100joursdezbeul.netlify.app/) le switch ne fonctionne pas (ça fonctionne correctement en dev local). Je ne suis pas familier de netlify (ni de svelte d'ailleurs :)), je me demande quoi en penser. Aucune erreur dans la console sur cette URL. As tu un avis sur la question ?

2023-05-12 12:33 UTC, cedricr commented
> @D4llo je me rends compte que sur [le deploy-preview](https://deploy-preview-112--100joursdezbeul.netlify.app/) le switch ne fonctionne pas (ça fonctionne correctement en dev local). Je ne suis pas familier de netlify (ni de svelte d'ailleurs :)), je me demande quoi en penser. Aucune erreur dans la console sur cette URL. As tu un avis sur la question ?

Je n'ai pas regardé le code, mais pour l'instant il n'y a pas de javascript activé dans le code généré, c'est sans doute pour ça. J'essayerai de regarder ce week-end ce qu'on peut faire.
Pour tester en local dans les memes conditions que déployé:
npm run build suivi de npm run preview

2023-05-14 11:07 UTC, juliemoynat requested changes

2023-05-14 11:07 UTC, juliemoynat commented on src/routes/+page.svelte
> +	<label for="perPopulation">Score / Habitants</label>
Comme il s'agit d'un groupe de champs radio, il faut un `fieldset` et une `legend` pour ce petit monde.

Je propose :

```html
<fieldset>
  <legend>Type de score</legend>

  <!-- Les champs ici -->
</fieldset>
```

2023-05-14 11:07 UTC, juliemoynat commented on src/routes/+page.svelte
> +	<label for="raw">Score</label>
Est-ce qu'on peut le caractériser afin d'être plus explicite ? "Score par défaut" ou autre ?

2023-05-14 11:07 UTC, juliemoynat commented on src/app.postcss
> +		background-color: #0084c7;
Ce bleu ne permet pas d'avoir un ratio de contraste correct avec le texte. Dans la PR #117, on change finalement pour le "blue-800" de TailwindCSS. Peut-on le changer ici ?

2023-05-14 11:07 UTC, juliemoynat commented on src/app.postcss
> +	/* radio buttons as on/off buttons */
L'implémentation réalisée ne permet de voir la prise de focus (touche tabulation du clavier). Voici un exemple d'implémentation pour corriger : https://codepen.io/copsae/pen/poaVwom

2023-05-14 16:46 UTC, florianMo commented on src/routes/+page.svelte
> +	<label for="perPopulation">Score / Habitants</label>
yes!

2023-05-14 16:47 UTC, florianMo commented on src/routes/+page.svelte
> +	<label for="perPopulation">Score / Habitants</label>
je fais ça, pas facile la culture de l'accessibilité :)

2023-05-14 16:48 UTC, florianMo commented on src/app.postcss
> +		background-color: #0084c7;
done

2023-05-14 16:48 UTC, florianMo commented on src/routes/+page.svelte
> +	<label for="raw">Score</label>
"Score brut" ?

2023-05-14 16:49 UTC, juliemoynat commented on src/routes/+page.svelte
> +	<label for="perPopulation">Score / Habitants</label>
Une fois formé·e, il y a plein de choses comme ça qui vont toutes seules 😜

2023-05-14 16:50 UTC, juliemoynat commented on src/routes/+page.svelte
> +	<label for="raw">Score</label>
Pourquoi pas mais j'ai vu après coup que ça ne semblait pas plaire à @D4llo donc je sais pas 😅

2023-05-14 16:55 UTC, florianMo commented on src/app.postcss
> +	/* radio buttons as on/off buttons */
J'ai ajouté une ombre portée (peut être un peu discrète)

![image](https://github.com/cedricr/100joursdezbeul/assets/3530297/fd0c5d9f-9673-4966-aa04-18ef986a17be)

2023-05-14 16:58 UTC, florianMo commented on src/routes/+page.svelte
> +	<label for="raw">Score</label>
ok :). Attendons des avis. Merci pour la revue a11y, très apprécié !

2023-05-14 17:07 UTC, juliemoynat commented on src/app.postcss
> +	/* radio buttons as on/off buttons */
Oui, pour moi, il faut qu'on ait quelque chose de plus proche de ce qu'on a ailleurs sur le site (l'outline par défaut).

2023-05-14 21:25 UTC, D4llo commented on src/routes/+page.svelte
> +	<label for="perPopulation">Score / Habitants</label>
ou `Score / Population` ?

Les deux me vont :)

2023-05-14 21:26 UTC, D4llo commented on src/routes/+page.svelte
> +	<label for="raw">Score</label>
Cela ne me semblait pas nécessaire mais du coup je m'aligne sur vous :+1:

2023-05-15 07:38 UTC, florianMo commented on src/app.postcss
> +	/* radio buttons as on/off buttons */
@juliemoynat j'ai changé pour le default outline

2023-05-15 10:59 UTC, juliemoynat commented on src/routes/+page.svelte
> +	<label for="perPopulation">Score / Habitants</label>
Score/Population me semble bien, ça évite un point médian.

2023-05-15 12:11 UTC, florianMo commented on src/routes/+page.svelte
> +	<label for="perPopulation">Score / Habitants</label>
OK pour `Score/Population`

2023-05-23 05:46 UTC, florianMo commented
@juliemoynat @D4llo est ce qu'il reste des choses à fix la dessus?

2023-05-25 15:58 UTC, cedricr commented
Désolé, j'arrive un peu tard, mais voilà mes remarques pour faire avancer ça.

J'aime bien l'idée de jouer avec la pondération (c'est moi qui ait créé l'issue au départ!), mais je trouve qu'on alourdi beaucoup la page d'accueil pour une fonctionnalité qui est expérimentale, et pour laquelle je n'ai pas vu une demande hallucinante.

Ça me paraitrait plus raisonnable de commencer par
- faire une page séparée des scores pondérés, qui permet d'expliciter aussi en une phrase, au dessus du classement, ce qu'on va voir
- ajouter un lien à partir du pied de page général vers cette page

À partir de là, on pourrait jouer un peu avec, demander aux gens ce qu'ils en pensent, et eventuellement le péréniser sur la page d'accueil comme proposé ici dans un second temps.
Ça permet aussi de contourner l'absence de js dans l'immédiat.

Au sujet de l'intitulé, s'il persiste dans les prochaines itérations: je trouve que Score/Population est peu lisible (bizarrement je lis ça instinctivement comme un choix: score OU population), alors que score/habitant·es est parfairement clair pour moi. Et je pense qu'on peut l'abbréger en score/hab. pour éviter le point médiant, mais au prix d'un peu de lisibilité?

En tout cas, merci pour le taf' accompli!

2023-05-25 16:06 UTC, florianMo commented
merci pour le feedback @cedricr , j'avais pas compris que sur le déploiement actuel (de production) il n'y avait pas non plus le bundle JS (je pensais que c'était juste sur le preview), donc en effet ça pose un souci pour cette PR.

2023-05-25 16:37 UTC, cedricr commented
@florianMo oui la preview est aussi proche de la prod que possible! Pas impossible qu'on ajoute du js en prod un jour ou l'autre, mais dans tous les cas ça me parait mieux sur une page à part, ça nous donne le temps d'y penser.

2023-05-25 16:42 UTC, florianMo commented
> @florianMo oui la preview est aussi proche de la prod que possible! Pas impossible qu'on ajoute du js en prod un jour ou l'autre, mais dans tous les cas ça me parait mieux sur une page à part, ça nous donne le temps d'y penser.

OK! Je vais essayer de faire ça semaine prochaine

2023-07-14 10:54 UTC, closed without merging