Ajout de l'interview de DavDuf
cedricr/100joursdezbeul pull request #122
Opened 2023-05-11 11:00 UTC by D4llo

Fix #120

2023-05-11 11:26 UTC, florianMo commented on src/lib/assets/media-refs.json
> +		"content": "Interview de David Duvfresne",
petite coquille sur "Dufresne"

2023-05-11 11:47 UTC, D4llo commented on src/lib/assets/media-refs.json
> +		"content": "Interview de David Duvfresne",
Bien vu !

2023-05-11 17:32 UTC, juliemoynat requested changes
L'ajouter à la liste me semble tout à fait normal. Toutefois, la vidéo n'étant pas sous-titrée, je propose à minima qu'on ajoute entre parenthèses "(vidéo malheureusement non sous-titrée)". Au moins les personnes sourdes et malentendantes n'iront pas espérer voir quelque chose qu'elles ne pourront pas entendre…

Autrement, je ne sais pas si le point a été soulevé auprès de Blast/David Dufresne ?

2023-05-11 17:32 UTC, juliemoynat commented on src/lib/assets/media-refs.json
> +		"source": "https://www.blast-info.fr/emissions/2023/intervilles-du-zbeul-la-fronde-sorganise-face-a-macron-Qz0zPGTRQcy6JupO0gJwUA",
Plutôt "Interview par" que "de" car c'est pas David Dufresne qui est interviewé 😉

2023-05-11 17:40 UTC, D4llo commented on src/lib/assets/media-refs.json
> +		"source": "https://www.blast-info.fr/emissions/2023/intervilles-du-zbeul-la-fronde-sorganise-face-a-macron-Qz0zPGTRQcy6JupO0gJwUA",
J'ai mis "Interview vidéo par David Dufresne (hélas non sous-titrée)" car plus court. Je passe en resolve pour le moment, mais n'hésite pas à refaire un retour :)

2023-05-11 17:56 UTC, juliemoynat approved these changes

2023-05-11 17:56 UTC, merged

2023-05-11 18:15 UTC, D4llo commented
Merci !

2023-05-12 11:42 UTC, cedricr commented
> Autrement, je ne sais pas si le point a été soulevé auprès de Blast/David Dufresne ?

Pas pendant l'interview en tout cas ; et je ne pense pas qu'on y ait pensé après (@hguemar ?)
On est en capacité de préparer les sous-titres nous-même et de les leur proposer éventuellement?

2023-05-12 16:58 UTC, juliemoynat commented
Franchement, vu la longueur de la vidéo, moi je pourrais pas. Mais ça se finance aussi ce genre de taff 😛

2023-05-12 18:32 UTC, D4llo commented
@juliemoynat et ça se crowdsource aussi :)