Personnalite
cedricr/100joursdezbeul pull request #129
Opened 2023-05-12 19:13 UTC by D4llo

Fix #128

2023-05-12 19:19 UTC, florianMo commented on src/lib/utils.ts
> +export function filterEventsForName(name: string, events: ActionEvent[]): ActionEvent[] {
Petit détail, je pense que typer le retour de ces fonctions est inutile, Typescript va être capable de les inférer. Globalement c'est une bonne pratique de ne pas expliciter un type si ce n'est pas nécessaire. Pour vérifier ça, tu peux supprimer le type de retour et survoler le nom de la fonction sous VSCode, tu verras que TS sait déjà ce que retourne cette fonction.

2023-05-12 19:32 UTC, D4llo commented on src/lib/utils.ts
> +export function filterEventsForName(name: string, events: ActionEvent[]): ActionEvent[] {
Tout le monde n'utilise pas VSCode.

2023-05-12 19:58 UTC, florianMo commented on src/lib/utils.ts
> +export function filterEventsForName(name: string, events: ActionEvent[]): ActionEvent[] {
C'est indépendant de ton IDE, c'est TS qui est en jeu ici. Mais c'est vraiment un détail :).

2023-05-12 20:04 UTC, D4llo commented on src/lib/utils.ts
> +export function filterEventsForName(name: string, events: ActionEvent[]): ActionEvent[] {
Yes perso je ne m'opposerai pas à leur suppression si on automatise ou si une personne veut s'en occuper.

2023-05-12 20:05 UTC, D4llo commented on src/routes/personnalite/[nom]/+page.svelte
> +</script>
Peut-être faire une gestion d'erreur ici au cas où.

Quand pensez-vous ?

2023-05-13 13:27 UTC, juliemoynat requested changes
Est-ce qu'on ne mettrait pas le total de points obtenus grâce à chaque personnalité dans la liste et en haut de leur page comme pour le classement par date ? 🤔

2023-05-13 13:27 UTC, juliemoynat commented on src/routes/personnalite/+page.svelte
> +					alt={`Photo de ${target.nom}`}
Image qu'on peut considérer comme décorative donc `alt=""` plutôt ;-)

2023-05-13 13:27 UTC, juliemoynat commented on src/routes/personnalite/+page.svelte
> +			<li class="mb-5 flex items-center gap-4 text-xl">
Plutôt qu'une liste ici, on devrait avoir le nom de la personnalité dans un titre `h3` (la structuration en titres est plus logique ici). Et le lien, au lieu de le rendre trop verbeux en encadrant la description de la personnalité, ne devrait englober que le nom de la personnalité. Ensuite, ce lien pourra s'étendre à tout le bloc via la classe `link-block` (se trouvant dans le fichier app.postcss).

Code HTML :

```html
<div style="position: relative">
  <img src="image.jpg" alt="" />
  <h3><a href="lien" class="link-block">Nom de la personnalité</a></h3>
  <p>Description de la personnalité</p>
</div>
```

2023-05-13 13:27 UTC, juliemoynat commented on src/routes/personnalite/[nom]/+page.svelte
> +		alt={`Photo de ${data.nom}`}
idem, `alt=""`

2023-05-14 18:11 UTC, D4llo commented on src/routes/personnalite/+page.svelte
> +			<li class="mb-5 flex items-center gap-4 text-xl">
C'est pas évident de connaître la différence entre link et link-block sans regarder :/

2023-05-14 18:17 UTC, juliemoynat commented on src/routes/personnalite/+page.svelte
> +			<li class="mb-5 flex items-center gap-4 text-xl">
Si tu veux, renomme la classe 😉

2023-05-14 18:20 UTC, D4llo commented on src/routes/personnalite/+page.svelte
> +			<li class="mb-5 flex items-center gap-4 text-xl">
je vais voir.

Pourquoi ne pas faire ?

```html
<a style="position: relative">
  <img src="image.jpg" alt="" />
  <h3>Nom de la personnalité</h3>
  <p>Description de la personnalité</p>
</a>
```

2023-05-14 18:23 UTC, juliemoynat commented on src/routes/personnalite/+page.svelte
> +			<li class="mb-5 flex items-center gap-4 text-xl">
Parce que pour une personne aveugle, ça fait un lien très verbeux, très long qui complexifie la navigation et la compréhension de la destination du lien.

2023-05-14 18:26 UTC, D4llo commented on src/routes/personnalite/+page.svelte
> +			<li class="mb-5 flex items-center gap-4 text-xl">
est-ce qu'il y a moyen de faire une sorte de read less/more dans un block pour diminuer la verbosité ?

genre "lien vers [nom de la personnalité]. Voulez vous naviguer ou connaitre la fonction de [nom de la personnalité] avant de décider de naviguer ?"

2023-05-14 18:28 UTC, juliemoynat commented on src/routes/personnalite/+page.svelte
> +			<li class="mb-5 flex items-center gap-4 text-xl">
Je suis pas sûre de comprendre. J'ai l'impression que ça augmente la complexité et la verbosité là 😅

2023-05-14 18:32 UTC, D4llo commented on src/routes/personnalite/+page.svelte
> +			<li class="mb-5 flex items-center gap-4 text-xl">
Aucune idée pour la complexité. Cela pourrait être natif.

2023-05-14 18:35 UTC, D4llo commented on src/routes/personnalite/+page.svelte
> +			<li class="mb-5 flex items-center gap-4 text-xl">
Est-ce que pour la verbosité, la lecture de l'écran peut-être coupée ? Genre si Alice veut passer la lecture, elle peut valider avant la fin de la lecture et si Bob veut se taper tout le titre de la personnalité, il peut laisser défiler ?

2023-05-14 18:48 UTC, juliemoynat commented on src/routes/personnalite/+page.svelte
> +			<li class="mb-5 flex items-center gap-4 text-xl">
Ah nativement, je ne vois pas comment ça pourrait être fait mais quoiqu'il en soit, ça n'existe pas.

Et oui, on peut couper la lecture mais comment être sûr·e qu'on ne loupe pas quelque chose pour comprendre la destination du lien dans ce cas ? 😉

2023-05-25 18:20 UTC, cedricr commented on src/routes/personnalite/[nom]/+page.svelte
> +</script>
Oui idéalement le build devrait échouer quand les données sont incorrectes

2023-05-25 18:24 UTC, cedricr commented on src/lib/assets/targets.json
> +	{
Les cibles sont maintenant gérées dans Grist: https://100joursdezbeul.getgrist.com/62uY9YoxQE56/100-jours-de-zbeul/p/2
On peut rajouter le champ Image si nécessaire.
L'URL en elysee.fr ou gouvernement.fr ne me parait pas forcement indispensable, on est pas obligés de leur faire de la pub. Wikipedia, pourquoi pas, mais on rajoutera les liens sur grist aussi alors. 
Tout ça se retrouvera donc dans le fichier cibles.json, qui est généré lors de la récupération des données Grist

2023-07-14 10:54 UTC, closed without merging