Ajout d'une page presse
cedricr/100joursdezbeul pull request #19
Opened 2023-04-26 15:48 UTC by D4llo

- [ ] Ajout d'une section revue de presse
- [ ] Ajout d'une section ressources à télécharger
- [ ] Ajout d'une section dossier de presse

2023-04-27 20:07 UTC, cedricr commented
C'est pas mal du tout! Un petit pb de rendu, et il faudrait affiner un peu les espacements
![image](https://user-images.githubusercontent.com/7826756/234978964-c6936e44-d99e-4ae8-b03a-6f5d5eedbbf1.png)

2023-04-27 22:02 UTC, D4llo commented
Que veut dire affiner ici ? plus large sur le vertical ? moins large ? ou est-ce entre les images et le contenu textuel ?

2023-04-27 23:12 UTC, D4llo commented on src/lib/utils.ts
> +import rawPresse from '$lib/assets/presse.json?raw';
le json import casse le code. Tu peux regarder ?

2023-04-28 10:39 UTC, cedricr commented on src/lib/utils.ts
> +import rawPresse from '$lib/assets/presse.json?raw';
:heavy_check_mark:

2023-04-28 10:46 UTC, cedricr commented
@D4llo j'ai corrigé les histoires d'import, ajouté un lien revue de presse sur la page d'accueil, et joué un peu sur les espacements.

Idéalement il faudrait encore:
- rapatrier les images en local plutôt que de les prendre distantes
- les optimiser
- rajouter les nouveux liens d'hier

Mais tout ça peut aussi venir plus tard dans une ou d'autres PR, à toi de voir

2023-04-28 11:03 UTC, cedricr requested changes

2023-04-28 14:45 UTC, hguemar commented
Contenu ok

2023-04-28 17:22 UTC, D4llo commented on src/lib/assets/media-refs.json
> +		"image": "http://s.regards.oonops.eu/5re8/ico/144x144.png"
C'est en cours

2023-04-28 19:04 UTC, cedricr submitted a review, later dismissed
C'est top; dans un second temps on pourrait peut-etre rajouter les dates des articles, et trier par date. ça sera interessant d'ici quelques semaines. Mais pour moi on peut merger en l'état

2023-04-28 19:06 UTC, D4llo commented on src/lib/assets/media-refs.json
> +		"image": "http://s.regards.oonops.eu/5re8/ico/144x144.png"
bon c'est bogué. faut que je regarde comment marche les ressources static en svelte

2023-04-28 19:12 UTC, cedricr submitted a review, later dismissed
Corrigé deux noms d'image, le build passe maintenant

2023-04-28 21:50 UTC, cedricr approved these changes

2023-04-28 23:37 UTC, D4llo commented
Allez hop je merge

2023-04-28 23:38 UTC, merged