feat: national statistics
cedricr/100joursdezbeul pull request #32
Opened 2023-04-27 21:41 UTC by supermarille

https://github.com/cedricr/100joursdezbeul/issues/20
Mais il manque l'affichage propre, je ne sais pas comment faire un truc joli...

2023-05-11 02:00 UTC, D4llo commented
Voilà un aperçu

![image](https://github.com/cedricr/100joursdezbeul/assets/131776117/e5646dff-55bc-4732-9d66-6d601c282105)

2023-05-11 02:25 UTC, D4llo commented
Je suis passé par des emojis pour le moment. Je vous propose de les garder sur le court terme et de faire une issue pour les remplacer ultérieurement.

2023-05-11 10:56 UTC, juliemoynat requested changes
Ça me semble bien !

J'ai relevé quelques coquilles dans le texte.

+ il faut ajouter cette page dans la page "Plan du site"

2023-05-11 10:56 UTC, juliemoynat commented on src/routes/+page.svelte
> +	<li><a href="/statistiques">Statistiques nationale</a></li>
Coquille : il manque un "S" à la fin de "nationale"

2023-05-11 10:56 UTC, juliemoynat commented on src/routes/statistiques/+page.svelte
> +<svelte:head><title>Statistiques nationale | 100 jours de zbeul</title></svelte:head>
Coquille : il manque un "S" à la fin de "nationale"

2023-05-11 10:56 UTC, juliemoynat commented on src/routes/statistiques/+page.svelte
> +	<h2 class="zbeul mb-16 mt-16 text-4xl">Statistiques nationale</h2>
Coquille : il manque un "S" à la fin de "nationale"

2023-05-11 10:56 UTC, juliemoynat commented on src/routes/statistiques/+page.svelte
> +			🚁 <span class="font-bold">{nationalStats.fuite}</span> fuites précipités d’une personnalité
Coquille : il manque un "e" à "précipités" pour avoir "précipitées"

2023-05-14 10:32 UTC, juliemoynat approved these changes

2023-05-14 10:34 UTC, merged